// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Organization.EntityFramework;

#nullable disable

namespace Organization.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231202203652_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Organization.Database.Entities.BusinessUnitEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyFk");

                    b.ToTable("Business units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CompanyFk = 1L,
                            Index = 0,
                            Name = "1"
                        },
                        new
                        {
                            Id = 2L,
                            CompanyFk = 1L,
                            Index = 1,
                            Name = "2"
                        },
                        new
                        {
                            Id = 3L,
                            CompanyFk = 1L,
                            Index = 2,
                            Name = "3"
                        },
                        new
                        {
                            Id = 4L,
                            CompanyFk = 1L,
                            Index = 3,
                            Name = "4"
                        },
                        new
                        {
                            Id = 5L,
                            CompanyFk = 1L,
                            Index = 4,
                            Name = "5"
                        },
                        new
                        {
                            Id = 6L,
                            CompanyFk = 2L,
                            Index = 0,
                            Name = "1"
                        },
                        new
                        {
                            Id = 7L,
                            CompanyFk = 2L,
                            Index = 1,
                            Name = "2"
                        },
                        new
                        {
                            Id = 8L,
                            CompanyFk = 2L,
                            Index = 2,
                            Name = "3"
                        },
                        new
                        {
                            Id = 9L,
                            CompanyFk = 2L,
                            Index = 3,
                            Name = "4"
                        },
                        new
                        {
                            Id = 10L,
                            CompanyFk = 2L,
                            Index = 4,
                            Name = "5"
                        },
                        new
                        {
                            Id = 11L,
                            CompanyFk = 3L,
                            Index = 0,
                            Name = "1"
                        },
                        new
                        {
                            Id = 12L,
                            CompanyFk = 3L,
                            Index = 1,
                            Name = "2"
                        },
                        new
                        {
                            Id = 13L,
                            CompanyFk = 3L,
                            Index = 2,
                            Name = "3"
                        },
                        new
                        {
                            Id = 14L,
                            CompanyFk = 3L,
                            Index = 3,
                            Name = "4"
                        },
                        new
                        {
                            Id = 15L,
                            CompanyFk = 3L,
                            Index = 4,
                            Name = "5"
                        },
                        new
                        {
                            Id = 16L,
                            CompanyFk = 3L,
                            Index = 5,
                            Name = "6"
                        },
                        new
                        {
                            Id = 17L,
                            CompanyFk = 3L,
                            Index = 6,
                            Name = "7"
                        },
                        new
                        {
                            Id = 18L,
                            CompanyFk = 4L,
                            Index = 0,
                            Name = "1"
                        },
                        new
                        {
                            Id = 19L,
                            CompanyFk = 4L,
                            Index = 1,
                            Name = "2"
                        },
                        new
                        {
                            Id = 20L,
                            CompanyFk = 4L,
                            Index = 2,
                            Name = "3"
                        },
                        new
                        {
                            Id = 21L,
                            CompanyFk = 4L,
                            Index = 3,
                            Name = "4"
                        },
                        new
                        {
                            Id = 22L,
                            CompanyFk = 4L,
                            Index = 4,
                            Name = "5"
                        },
                        new
                        {
                            Id = 23L,
                            CompanyFk = 4L,
                            Index = 5,
                            Name = "6"
                        },
                        new
                        {
                            Id = 24L,
                            CompanyFk = 4L,
                            Index = 6,
                            Name = "7"
                        });
                });

            modelBuilder.Entity("Organization.Database.Entities.CompanyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrganizationFk")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationFk");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Index = 0,
                            Name = "Child 1",
                            OrganizationFk = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Index = 1,
                            Name = "Child 2",
                            OrganizationFk = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Index = 2,
                            Name = "Child 3",
                            OrganizationFk = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Index = 0,
                            Name = "Child 1",
                            OrganizationFk = 2L
                        });
                });

            modelBuilder.Entity("Organization.Database.Entities.OrganizationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Index = 0,
                            Name = "Organization 1"
                        },
                        new
                        {
                            Id = 2L,
                            Index = 1,
                            Name = "Organization 2"
                        });
                });

            modelBuilder.Entity("Organization.Database.Entities.BusinessUnitEntity", b =>
                {
                    b.HasOne("Organization.Database.Entities.CompanyEntity", "Company")
                        .WithMany("BusinessUnits")
                        .HasForeignKey("CompanyFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Organization.Database.Entities.CompanyEntity", b =>
                {
                    b.HasOne("Organization.Database.Entities.OrganizationEntity", "Organization")
                        .WithMany("Companies")
                        .HasForeignKey("OrganizationFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Organization.Database.Entities.CompanyEntity", b =>
                {
                    b.Navigation("BusinessUnits");
                });

            modelBuilder.Entity("Organization.Database.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
